### ISSUE TITLE
Fix semantic bugs found by the KAIST team

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#708]
- [ ] [a source operand is confused with the destination](SoftSec-KAIST/MeanDiff#1)
  Yeah, it is indeed obvious from the sources that dst and src operands are flipped. So it will affect all cases, not only when operands are equal or indirect. 
- [ ] [a source operand depends on the destination](SoftSec-KAIST/MeanDiff#2)
  This is actually a family of bugs, that should affect not only `sub`, but all other arithmetic operations, that computes flags. The problem is when the computation of a source operand is data dependent on the value of the destination. So after we computed the destination, the source is no longer valid. We should store the value of a source expression to a temporary variable. There is another [manifestation](SoftSec-KAIST/MeanDiff#2) of this bug. The [xadd](SoftSec-KAIST/MeanDiff#7) is also from this family, but is a worse version, as it doesn't even store the destination. 
- [ ] [small immediates are not sign-extended](SoftSec-KAIST/MeanDiff#4)
  It looks like that we may have the same issue with many other instructions, not only with `pop`, so we should walk carefully through the whole 2B and check all the sign-extensions. 
- [ ] [count in shifts should be taken module operand size](SoftSec-KAIST/MeanDiff#6)
  It also produces [bogus self assignments](#706), we also should check shift instructions. 
- [ ] [broken flag calculation in `xadd`](SoftSec-KAIST/MeanDiff#7)
   The `CF` flag is definitely broken, but I believe that other flags are also computed incorrectly. The `set_flags_add` function, here is applied incorrectly, as we should pass values that were originally stored in source and destination. Since here both the source and the destination are modified we get wrong results. 
- [ ] [memory alignment is not enforced](SoftSec-KAIST/MeanDiff#8)
   Indeed we ignore the alignment issues with the floating point instructions. However, before fixing this bug, I would suggest to resolve #705 and probably move this family of instructions to the new lifter.

**Comment by gitoleg** [comment]
List of PRs that fix this issue:

-  `xadd` instruction operands and CF flag https://github.com/BinaryAnalysisPlatform/bap/pull/724
 -  `sub` flags when source depends on the destination https://github.com/BinaryAnalysisPlatform/bap/pull/728
 - small-imm extending https://github.com/BinaryAnalysisPlatform/bap/pull/727
 - `mod size` for rotate instructions https://github.com/BinaryAnalysisPlatform/bap/pull/725
 - `pshufb` memory alignment https://github.com/BinaryAnalysisPlatform/bap/pull/726

**Comment by ivg** [comment]
Thanks!
